### ISSUE TITLE
Légende de l'évolution des vaccination erronée

### ISSUE THREAD

**Issue by jecisc** [rozierguillaume/covidtracker-tools#125]
Bonjour,

Sur la page "vaccintracker" (https://covidtracker.fr/vaccintracker) la légende d'un des graphique semble être erronée. "cumul vaccinés (1 ou 2 dose)" et "cumul vaccinés (2 doses)" semblent être inversés sur le graphique ainsi que dans la légende au dessus. 

![image](https://user-images.githubusercontent.com/9519971/106370831-1d9f8000-635e-11eb-83ef-3cdcad02bda8.png)
![image](https://user-images.githubusercontent.com/9519971/106370832-209a7080-635e-11eb-85f3-c3e09e9c5ccd.png)

**Comment by jecisc** [comment]
Également, la légende sur la moyenne quotidienne de vaccination semble avoir un problème d'affichage:

![image](https://user-images.githubusercontent.com/9519971/106370937-512eda00-635f-11eb-9c0c-87ab222df0c1.png)

**Comment by rozierguillaume** [comment]
Merci c'est corrigé, ça sera à jour d'ici quelques minutes sur le site.
