### ISSUE TITLE
Mettre à jour l'échelle de répartition des vaccinés par département

### ISSUE THREAD

**Issue by pedugnat** [rozierguillaume/covidtracker-tools#213]
Sur VaccinTracker, l'échelle de couleur de "Répartition des vaccinés" par département est hardcodée, et n'est plus à jour (cf. capture ci-joint).

Il suffirait de modifier les valeurs dans `var tableauValeurs = [6, 7, 8, 9, 10]` (https://github.com/rozierguillaume/covidtracker-tools/blob/main/src/VaccinTracker/carteDepartementJs.php#L34)

![image](https://user-images.githubusercontent.com/34744445/113131145-20fb9e80-921d-11eb-971d-c046ad9e1180.png)

**Comment by Dufgui** [comment]
guillaume rozier already commit auto calcul of legend.

**Comment by Dufgui** [comment]
i just clean the code (remove console.log and remove unused variable)

**Comment by E-Dmz** [comment]
Hi, i think that issue has not been fixed yet, at least for the deps (see screenshot). I'm new to github, and I don't understand from your previous exchange if the issue has been considered fixed or not.

![Screenshot_20210415_113655](https://user-images.githubusercontent.com/74925515/114848584-204b3680-9ddf-11eb-9a57-6873d6965433.png)
