### ISSUE TITLE
Ajouter rel="noreferrer noopener" sur les liens Doctolib & co

### ISSUE THREAD

**Issue by DavidLibeau** [rozierguillaume/covidtracker-tools#221]
Pour des raisons de sécurité et de confidentialité, les liens externes vers Doctolib et autres fournisseurs de rendez-vous de vaccination doivent avoir l'attribut `rel="noreferrer noopener"`.

https://github.com/rozierguillaume/covidtracker-tools/blob/main/src/ViteMaDose/vitemadoseJs.php#L98

**Comment by BrunoSpy** [comment]
Le code a beaucoup évolué et est à présent ici : https://github.com/CovidTrackerFr/vitemadose-front
