### ISSUE TITLE
le vaccinodrome de Vannes est absent dans le 56-Morbihan !

### ISSUE THREAD

**Issue by fjoussellin** [rozierguillaume/covidtracker-tools#248]
Bonjour, 
Le vaccinodrome de Vannes ne semble pas répertorié par Vitemadose ... 
Son adresse est : **Centre de vaccination - Vannes Kercado 28 Rue Winston Churchill, 56000 Vannes** (c'est le gymnase de Kercado). 
On peut facilement le retrouver sur doctolib :  https://www.doctolib.fr/hopital-public/vannes/centre-de-vaccination-covid-19-vannes-kercado
alors que sur Vitemadose, il semble répertorié à l'adresse : https://partners.doctolib.fr/hopital-public/vannes/ghba-centre-de-vaccination-covid-vannes 

Merci pour cet excellent outil, 
Bon courage à tous, 
François

**Comment by BrunoSpy** [comment]
Transféré https://github.com/CovidTrackerFr/vitemadose/issues/253
