### ISSUE TITLE
Echelle ou Courbes incorrectes vaccin tracker

### ISSUE THREAD

**Issue by CyrilFISCHER** [rozierguillaume/covidtracker-tools#263]
Bonjour,

Si on additionne la courbe la courbe bleu clair (1ere injection) avec la courbe bleu foncé(2nd injection) on dépasse la courbe grise(Doses reçus).
Sur la capture ci-jointe pourtant 13.5M + 5.4M = 19M < 22.3M
De plus on peut voir par exemple que la courbe bleu clair à 13.5M dépasse les 15M sur l'axe des ordonnées

![image](https://user-images.githubusercontent.com/40919721/116234104-76fc2d00-a75c-11eb-96b8-449713ab02ee.png)

**Comment by BrunoSpy** [comment]
La courbe bleu clair et la courbe bleu foncé sont déjà empilées, c'est donc la somme des deux qu'il faut lire.
Par ailleurs, nous sommes en train de revoir ce graphique pour le rendre plus lisible.
