### ISSUE TITLE
[BUG] VaccinPlanner ne fonctionne plus

### ISSUE THREAD

**Issue by bokub** [rozierguillaume/covidtracker-tools#267]
Hello,
Quand j'essaie de passer à l'étape 3 de [VaccinPlanner](https://covidtracker.fr/vaccinplanner/), ça ne fonctionne pas car il y a une variable non définie:

`Uncaught ReferenceError: dejaVaccinesNb is not defined`

Visiblement ça vient de la dernière ligne de cette fonction:

https://github.com/rozierguillaume/covidtracker-tools/blob/d024c880e9a5b0a406c2732049fee11728c5cf36/src/VaccinPlanner/vaccinplanner.php#L842-L849

Voilà, bonne soirée

**Comment by bokub** [comment]
Après une petite enquête, je pense que le problème est à cause de **la ligne 584** de cette fonction:

https://github.com/rozierguillaume/covidtracker-tools/blob/d024c880e9a5b0a406c2732049fee11728c5cf36/src/VaccinPlanner/vaccinplanner.php#L570-L587

En effet, dans [le JSON de données](https://raw.githubusercontent.com/rozierguillaume/vaccintracker/main/data/output/vacsi-fra.json), la clé `n_dose1_cumsum` n'existe pas !

**Comment by bokub** [comment]
Visiblement la clé a simplement été renommée

Pull request ouverte pour régler le bug: #268

**Comment by BrunoSpy** [comment]
Corrigé ! Merci !
