### ISSUE TITLE
ViteMaDose - Problème de remontée KelDoc

### ISSUE THREAD

**Issue by chabrulat** [rozierguillaume/covidtracker-tools#270]
Bonjour,

Les centres utilisant la plateforme KelDoc ne sont plus remontés dans ViteMaDose.

Cordialement,

**Comment by chabrulat** [comment]
C'est rétabli, merci.

**Comment by chabrulat** [comment]
De nouveau le cas,

Cordialement,

**Comment by BrunoSpy** [comment]
Les problèmes pour ViteMaDose peuvent être remontés sur ce dépôt : https://github.com/CovidTrackerFr/vitemadose

Merci !
