### ISSUE TITLE
Ajout d'un filtre par type de vaccin dans la recherche vitemadose

### ISSUE THREAD

**Issue by pantshee** [rozierguillaume/covidtracker-tools#275]
Bonjour, 
Certaines personnes souhaitent éviter certains vaccins (par peur ou par contre indication médicale). 
Il serait utile de pouvoir ajouter avant ou après la recherche par ville, des cases à cocher (ou autre) avec les différents vaccins, afin d'affiner la recherche de doses.

Pour certains centres qui proposent plusieurs types de vaccins la complexité est un peu plus grande j'imagine, mais ce serait pertinent d'ajouter ce filtre au moins pour exclure de la recherche les centres de vaccination qui proposent 1 seul vaccin qu'on ne recherche pas

**Comment by chabrulat** [comment]
Les remarques concernant ViteMaDose peuvent être remontés sur ce dépôt : https://github.com/CovidTrackerFr/vitemadose

Cordialement,

**Comment by pantshee** [comment]
@chabrulat mince je me suis trompé de dépôt... merci pour la remarque, j'annule cette fiche
