### ISSUE TITLE
Les graphiques du dashboard région ne sont plus à jour depuis le 25 avril

### ISSUE THREAD

**Issue by Aymerik** [rozierguillaume/covidtracker-tools#278]
Remonté par @lc-dx sur Mattermost

https://covidtracker.fr/dashboard-regions/

**Comment by Micsou** [comment]
![image](https://user-images.githubusercontent.com/4601910/118122306-f93e4f80-b3f2-11eb-9879-5e095ff53292.png)
 Me semblé réglé @Aymerik
