### ISSUE TITLE
Affichage injections quotidiennes Vaccintracker

### ISSUE THREAD

**Issue by EliasOrphelin** [rozierguillaume/covidtracker-tools#281]
J'ai l'impression qu'il y a un bug dans le calcul de l'objectif, et que du coup l'axe y est tronqué : 
![image](https://user-images.githubusercontent.com/82414104/118378874-dff5f880-b5d6-11eb-85c5-833254a10031.png)

**Comment by rozierguillaume** [comment]
Normalement c'est corrigé. Tu peux les dire si c'est bon ?

**Comment by rozierguillaume** [comment]
(En prod)

**Comment by EliasOrphelin** [comment]
yes t'es trop fort. C'est mieux sans l'objectif je trouve
