### ISSUE TITLE
`proportionAVaccinerImmu` doit passer de 60% à 80%

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [rozierguillaume/covidtracker-tools#308]
En raison du taux de propagation des nouveaux variants, la proportion de personnes à vacciner pour atteindre une immunité collective doit être évaluée à 80% plutôt que 60%.

sources : 
https://fr.wikipedia.org/wiki/Variants_Kappa_et_Delta_du_SARS-CoV-2
https://www.lesechos.fr/politique-societe/societe/covid-le-variant-delta-peut-il-provoquer-une-quatrieme-vague-en-france-1327856

**Comment by r9mp** [comment]
Je me permets un ajout.
La proportion de personne à vacciner est de : 1 - 1 / (R0 souche initiale * augmentation variant alpha * augmentation variant delta * efficacité du vaccin).
R0 initial : 2.5 (d'où les 60% sur le site (1 - 1 / 2.5 = 0.6 = 60/100 = 60% ))
Le variant Alpha est considéré 50 % plus contagieux que la souche initiale (j'ai trouvé des chiffres de 30% à 70% ; j'ai mis au milieu).
Le variant Delta est 50% plus contagieux que l'alpha (j'ai trouvé entre 40% et 60% selon les sources, j'ai mis au milieu).
L'efficacité des vaccins quant au Delta semble de 90% (légères variations selon les vaccins ; ça devient compliqué ...).

=> 1 - 1 / (2.5 * 1.5 * 1.5 * 0.9) = 0.8

Ce chiffre ne prends pas considération qu'une partie de la population ayant déjà attrapé la maladie, elle a elle aussi une probabilité de la ré-attraper inférieure à 100% (ce qui vient baisser les 0.8 ; mais il faudrait ajouté les personnes ayant été testés positives sur les derniers mois (facile en soit mais combien de mois ?!)).

Si vous voulez, je peux faire une PR quant à cette modification ; éventuellement faire un truc un peu complet avec onglets pour montrer les variations de % de vaccination en fonction des variants. Après quant au texte explicatif ...

**Comment by r9mp** [comment]
Eratum : Il y a une PR à ce sujet : #304
