### ISSUE TITLE
Comment contribuer

### ISSUE THREAD

**Issue by HEYGUL** [rozierguillaume/covidtracker-tools#68]
Bonjour,

En naviguant sur VaccinTracker, j'ai remarqué que chaque carte vaccin est un élément `button`.
J'ai donc créé un fork dans l'idée de proposer une PR de modification de ces cartes afin d'éviter de la confusion chez les utilisateurs (notamment ceux utilisant un lecteur d'écran).

Je vois dans quel fichier faire les modifications, mais je ne sais pas comment lancer le site en local pour tester mes modifications avant d'ouvrir la PR.

Pouvez-vous m'aider à lancer le site en local ?

Merci

**Comment by Micsou** [comment]
Bonjour, 
Les fichiers sont intégrés dans un wordpress, du coup j'ai émulé les pages wordpress avec les fichiers test.php. 
Michael

**Comment by HEYGUL** [comment]
Merci @Micsou  pour votre réponse.
Je vais regarder comment m'en sortir avec le fichier `test.php` et un docker en local.

**Comment by Micsou** [comment]
Ah ouais, moi je fais une allergie à Docker ;) 
Je fais ça sur un WAMP...
Bon courage !

**Comment by HEYGUL** [comment]
Docker m'aura pris 5 minutes.
Je laisse l'issue ouverte, le temps que j'ouvre une PR avec le fichier `docker-compose.yml` et une documentation pour les éventuels futurs contributeurs.

**Comment by rozierguillaume** [comment]
Merci infiniment, super idée ça sera très utile !

**Comment by HEYGUL** [comment]
J'ai donc ouvert une PR: https://github.com/rozierguillaume/covidtracker-tools/pull/73.
Bonne lecture !
