### ISSUE TITLE
Proportion de personnes vaccinées

### ISSUE THREAD

**Issue by chabrulat** [rozierguillaume/covidtracker-tools#77]
Bonjour,

Sachant qu'il n'est pas prévu de vacciner les enfants pour l'instant (https://www.francetvinfo.fr/sante/maladie/coronavirus/vaccin/infographie-quand-pourrez-vous-vous-faire-vacciner-contre-le-covid-19_4229329.html) et que les 0-17 ans représentent  environ 21.25% de la population au 01/01/2020 (https://www.ined.fr/fichier/s_rubrique/155/copie.de.pop.totale.france.metro.fr.xls), ne vaudrait-il pas mieux calculer les différents pourcentages sur la population adulte (pourcentage de personnes vaccinées et pourcentage à atteindre) ?

Cordialement,

**Comment by rozierguillaume** [comment]
Bonjour,
Merci pour votre remarque intéressante. Vous avez raison. Mais je pense qu'il est préférable de laisser comme c'est actuellement par simplicité de lecture. Je rajouterai cependant des précisions pour indiquer que 21% des français ne sont pas "vaccinables". Merci !
